/**
 * Initial form state as a flat object.
 */
export default {
  Variant: "T Shape",
  RotorDiskRadius: "0",
  RotorDiskInnerRadius: "0",
  DiskThickness: "0",
  MagnetLength: "0",
  MagnetWidth: "0",
  MagnetThickness: "0",
  MagnetMaterial: "Neodymium",
  NumberMagnet: "0",
  InnerDistanceBetweenMagnets: "0",
  StatorThickness: "0",
  MechanicalClearance: "0",
  CoilType: "0",
  NumberOfCoilsPerPhase: "0",
  CoilLegWidth: "0",
  CoilInnerWidth1: "0",
  CoilInnerWidth2: "0",
  VerticalPlaneAngle: "0",
  HorizontalPlaneAngle: "0",
  Offset: "0",
  BracketLength: "0",
  BracketWidth: "0",
  BracketThickness: "0",
  BoomLength: "0",
  BoomPipeRadius: "0",
  BoomPipeThickness: "0",
  VaneLength: "0",
  VaneThickness: "0",
  VaneWidth: "0",
  HubHolesPlacement: "0",
  HubHoles: "0",
  Holes: "0",
  MetalLengthL: "0",
  MetalThicknessL: "0",
  FlatMetalThickness: "0",
  YawPipeDiameter: "0",
  PipeThickness: "0",
  RotorInnerCircle: "0",
  ResineRotorMargin: "0"
};
