/**
 * Initial form state as a flat object.
 */
export default {
  RotorDiskRadius: "",
  RotorDiskInnerRadius: "",
  DiskThickness: "",
  MagnetLength: "",
  MagnetWidth: "",
  MagnetThickness: "",
  MagnetMaterial: "",
  NumberMagnet: "",
  InnerDistanceBetweenMagnets: "",
  StatorThickness: "",
  MechanicalClearance: "",
  CoilType: "",
  NumberOfCoilsPerPhase: "",
  CoilLegWidth: "",
  CoilInnerWidth1: "",
  CoilInnerWidth2: "",
  VerticalPlaneAngle: "",
  HorizontalPlaneAngle: "",
  Offset: "",
  BracketLength: "",
  BracketWidth: "",
  BracketThickness: "",
  BoomLength: "",
  BoomPipeRadius: "",
  BoomPipeThickness: "",
  VaneLength: "",
  VaneThickness: "",
  VaneWidth: "",
  HubHolesPlacement: "",
  HubHoles: "",
  Holes: "",
  MetalLengthL: "",
  MetalThicknessL: "",
  FlatMetalThickness: "",
  YawPipeDiameter: "",
  PipeThickness: "",
  RotorInnerCircle: "",
  ResineRotorMargin: ""
};
